baseURL = "https://awalpremi.com/"
languageCode = "en-us"
title = "Prem"
theme = "hugo-brewm"

[params]
  description = "AI, software, markets, and writing."
  copyright = "Copyleft 2026 &copy; Awal Premi"
  extMeta = true
  ZenMode = false

  [params.logo]
    logoType = true

  [params.author]
    name = "Awal Premi"
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  stage = "stage"
  author = "author"
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
