baseURL = "https://awalpremi.com/"
languageCode = "en-us"
title = "Prem"
theme = "hugo-brewm"

[params]
  description = "AI, software, markets, and writing."
  copyright = "Â© 2026 Awal Premi"
  extMeta = true
  ZenMode = false

  unifiedFooter = true
  DisableFootBar = true
  HideHugoCredit = true

[params.posts]
  colophon = true

  [params.logo]
    logoType = true

  [params.author]
    name = "Awal Premi"
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  stage = "stage"
  author = "author"
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[params.analytics]
  append = 'head'